### PR TITLE
A few things I was wondering about

### PR DESCRIPTION
**Pull request by jonsterling**
There were a few things I was wondering about. First, the bits like:

``` objc
if (_numberOfSections > 0) {
  // calculation based on _metrics array
} else if (_numberOfItemsInSectionBlock) {
  // same calculation, but pulling data directly from the delegate
}
```

What's the purpose of these? If they're not necessary, you can merge this pull request. Otherwise, I'm a little curious… Thanks!

(The last thing I changed was I removed a bit of dead code.)

### CODE REVIEW

**Comment by kolinkrewinkel** [comment]
I'm pretty sure they were for if the cells were already created... lemme check.

**Comment by kolinkrewinkel** [comment]
Ok, I'll need to debug what the _numberOfSections variable has going on.

**Comment by jonsterling** [comment]
All right. I'm going to close this, since it can't be automatically merged anyway. It's certainly not a big deal, and we can deal with it later if we feel like it.

**Comment by kolinkrewinkel** [comment]
Cool, thanks.

**Pull request closed without merging**
