### PR TITLE
Do not run the static analyzer during build

### PR DESCRIPTION
**Pull request by zoul**
I don’t think it’s a good idea to run the static analyzer during each build, as it taxes the build time for the project that uses the library. Non-trivial projects usually use several libraries and if each of them run the analyzer, the build time would grow needlessly.

### CODE REVIEW

**Comment by zoul** [comment]
(Ah, sorry, the previous commits also crept into the pull request.)

**Comment by orta** [comment]
As the static analysis is only ran when cleaned, first compiled, or something changed is it really such a bad thing? I know I like to know that all the code ran in my project has been statically checked, it's not as good as a close audit but when working with others on a project who may have imported it that I trust, it sure is useful to me.

**Comment by zoul** [comment]
I fully agree that static checking (plus unit testing) is a desirable thing to have. But I think that libraries and frameworks should be _very_ careful about build times, since even small delays add up in the main project. You’re right, the analyzer is only run during clean builds, but those are surprisingly common, at least in my workflow. And you can always analyze the whole project by pressing Cmd-Shift-B (and run the tests with Cmd-U), so the tools are quite at hand even without being tied to the build.

**Comment by orta** [comment]
Well, you convinced me :+1:

**Comment by jonsterling** [comment]
I'm certainly open to the idea! As for the other commits that crept in, they seem good as well. I'd just like to test it and make sure things work as expected, and then I'll merge it in.

Thanks for contributing! :)

**Comment by zadr** [comment]
Would it make any sense to only run static analyzer during, say, release builds and not debug/development builds?

**Comment by zoul** [comment]
That would solve my issue with build times, I don’t think that people are extra sensitive to release build times. I’m not sure if such change would be for better or worse for the library developers – it seems easier to me to just hit Cmd-Shift-B than to make a release build before pushing new changes.

**Comment by zadr** [comment]
Analyzer on Release is a nice safety net.

It is very easy to forget to hit that key combo before making a push -- and it is very bad for a framework to have any obvious bugs. Losing a few days to track down a bug in third party code is a much worse feeling than a few seconds every few days to a build.

**Comment by kolinkrewinkel** [comment]
I agree with the profiles/debug/release differentiation - seems like the best route.  I'll check out the other commits too. :)

**Comment by zoul** [comment]
OK, analyzer in the Release build is a good option. Closing.

**Pull request closed without merging**
