### PR TITLE
Implementation for #16, Automatic Headers/Footers

### PR DESCRIPTION
**Pull request by jonsterling**
I've added `-gridView:titleForHeaderInSection:` and `-gridView:titleForFooterInSection:` to `<KKGridViewDataSource>`. These should behave as expected.

Consumers may continue to provide their own views in the usual way if they desire to do so.

### CODE REVIEW

**Comment by kolinkrewinkel** [comment]
Just curious, what do the automatic implementations look like?

**Comment by jonsterling** [comment]
Pretty much like the demo ones you wrote. I spruced up the colors a tiny bit, but basically the same. Here's a screenshot:

Defaults

**Comment by jonsterling** [comment]
I think at some point, it may be beneficial to try to make the defaults look like `UITableView`, incidentally.

**Comment by kolinkrewinkel** [comment]
Okay, that looks nice.  Later on I'll change them to Apple's default style.

**Comment by jonsterling** [comment]
Cool!

**Pull request merged**
