### PR TITLE
loads section header & footers on insert

### PR DESCRIPTION
**Pull request by keichan34**

### CODE REVIEW

**Comment by kolinkrewinkel** [comment]
Haha, best bugfix ever.  One line to an issue I couldn't figure out for weeks.

**Comment by jonsterling** [comment]
Has this been merged?

**Comment by kolinkrewinkel** [comment]
Well, it was supposed to be.  But it doesn't appear to be so.

**Comment by kolinkrewinkel** [comment]
Try pulling and updating the pull request, Keitaroh.

**Comment by jonsterling** [comment]
Well, I can merge this manually. So, hang on, everyone!

**Comment by kolinkrewinkel** [comment]
Oh, ok.  I can't because I'm logging off for tonight.  I'll start working again tomorrow. :)

**Pull request merged**
