### PR TITLE
More changes! (features + performance + general improvements)

### PR DESCRIPTION
**Pull request by zadr**
This change set is rather big, and I'll be happy to break it up into a few smaller pull requests if desired. I _think_ I managed to avoid using any tabs, so, the formatting should be good. And, of course, everything works fine in my testing, however, no one's perfect, and I may have missed things.

(Specifically: I do not have multiple selection enabled, and do my own custom highlighting/selection states in KKGridViewCell subclasses, so bugs may lie there.).

Anyway, please do let me know if there's anything else that needs changing with anything in this pull request, and without further ado, what was actually changed:
##### New

KKGridView
- Add ability for rows to have backgrounds that take up the width of the gridview
##### Misc changes:

KKGridViewSectionInfo
- Use @compatibility_alias instead of a set of empty subclasses for KKGridView{Footer, Header}

KKGridView
- How cell selection/highlight takes place, to avoid selection on the Press -> Scroll -> Release flow 
- Avoid drawing a cell on half-pixel points
- Use KVO instead of UIScrollViewDelegate methods
- Only layout cells when the cell size/padding is set and changed, not every time it is set
##### Performance-related changes:

KKGridView
- Cache -indexPathForIndex:0 inSection:0, since this is used a lot
- Don't remove cells from the gridview; its faster to set them hidden and alpha to 0.

KKGridViewCell
- Don't make _selectedBackgroundView or _contentView until it is first accessed by its getter (speeds up init)
- Don't remove cells from the gridview; its faster to set them hidden and alpha to 0.

KKGridViewUpdateStack
- Don't sort the update stack every time an item is added (allows for faster batching in addUpdates:)
- Use a dictionary lookup for most operations, instead of iterating through an array over and over

### CODE REVIEW

**Comment by jonsterling** [comment]
Thanks for all your hard work!

**Comment by zadr** [comment]
Not a problem; thank you for making this in the first place!

**Comment by jonsterling** [comment]
There's a new issue with deletion… In the demo, try pressing the delete button, and then trying to scroll; all the cells in the first section start spinning around and freaking out.

I may have messed this up in some of my in-between changes, but I just wanted to see if you had any insight into this before I went looking.

**Comment by zadr** [comment]
Unsure. It works fine if the section goes offscreen, and comes back on screen. I can look into it a bit.

Also, unrelated, but, -_respondToBoundsChange calls -reloadData, and -setNeedsLayout, and -reloadData also calls -setNeedsLayout.

**Comment by jonsterling** [comment]
Thanks. I think @kolinkrewinkel is now looking into the issue I mentioned (#129).

As for the multiple calls to `-setNeedsLayout`, can you make a new issue for that? Then one of us can look into rejiggering that.

**Pull request merged**
