### PR TITLE
C++ Excision

### PR DESCRIPTION
**Pull request by jonsterling**
Without too much extra work, we can replace the STL stuff with plain C arrays.

I way overestimated the complexity of what we were doing with this stuff; as it is, I can't think of a good justification for continuing to use the STL. Please look over these changes and let me know if I've done something extremely stupid in the process!

Additionally, with some refactoring, I was able to get this diff to a net loss in LOC.

(Never mind that footer bug I mentioned; I must have been on crack.)

### CODE REVIEW

**Comment by kolinkrewinkel** [comment]
How's the speed?

**Comment by jonsterling** [comment]
Haven't tried it on my phone yet, but I'd be very surprised if it is slower than the C++. It's likely faster. I'll try it out and let you know.

**Comment by kolinkrewinkel** [comment]
Sweet, thanks.

**Comment by jonsterling** [comment]
I'm playing with it on my phone now, and it's really slow. But I didn't try it before I made the changes. Did I make it worse?

**Comment by kolinkrewinkel** [comment]
It's fast regularly..

**Comment by jonsterling** [comment]
Well, go ahead and try it and let me know if you think it's different. If it sucks, then we'll revert.

**Comment by kolinkrewinkel** [comment]
It seems fine to me.

**Comment by jonsterling** [comment]
OK, fine. I'm about to push some improvements to the code.

**Comment by kolinkrewinkel** [comment]
Sweet.

**Pull request merged**
